# # print(7+8)
# # print(13-8)
# # print(30*40)
# # print(12/4)
# # print(13%5)
# # print(13**5)
# # print(13//5)
# # print(((3-4)*2-7)/8)
# # print("apple"+"Juice")
# #print(3==5)
# print(3!=5)
# #print(3>5)
# print(3<5)
# #print(3>=5)
# print(3<=5)
# print("jiwon"<"kanghee")
# print("jiwon"<"heechan")
# print("kanghee"<"heechan")
# print("kanghee"<"kanghYeon")
print(True and True)
print(True or True)
print(True and False)
print(False or False)
print(False or True)
print (not(True and False)or True)
print(True + False)
